# Build and deploy DocC to GitHub pages. Based off of Pointfree's work here:
# https://github.com/pointfreeco/swift-parsing/blob/main/.github/workflows/documentation.yml
name: Deploy Tuist Docc

on:
#   release:
#     types:
#       - published
  push:
    branches:
      - main

concurrency:
  group: tuist-docc-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-13
    steps:
      - name: Checkout Package
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Build documentation
        run: make docs/tuist/build
      - name: Fix permissions
        run: 'sudo chown -R $USER .build/documentation'
      - name: Deploy production to Netlify
        uses: jsmrcaga/action-netlify-deploy@v2.0.0
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_DEPLOY_TO_PROD: true
          NETLIFY_DEPLOY_MESSAGE: "Deployed from GitHub action"
          build_directory: './.build/documentation'
          install_command: "echo Skipping installing the dependencies"
          build_command: "echo Skipping building the web files"